@startuml
'!theme plain
skinparam componentStyle uml2
hide members
top to bottom direction
' skinparam linetype ortho
skinparam nodesep 35
skinparam ranksep 25

package "Controller (Transmit)" {
  class "SignalTransmitter" as SignalTransmitter
  class "PhysicalController" as PhysicalController
}

package "Controller (Receive)" {
  interface "ISignalReceiver" as ISignalReceiver
  class "SignalReceiver" as SignalReceiver
  class "PlayerController" as PlayerController
}

package "Game Engine" {
  class "Game" as GameMain
  class "Settings" as Settings
  class "Player" as Player
  class "Vehicle" as Vehicle
  class "TrackModule" as TrackModule
  class "Line" as Line
  class "Lane" as Lane
  class "DrivingProfile" as DrivingProfile

  GameMain *-- Settings
  GameMain *-- Player
  GameMain *-- TrackModule
  Player *-- Vehicle
  TrackModule *-- Line
  Line *-- DrivingProfile
  Line o-- Lane
}

package "Display" {
  class "DisplayManager" as DisplayManager
  class "LedDisplay" as LedDisplay
  class "ColorConstants" as ColorConstants
  class "Config" as Config
  class "RoundCounter" as RoundCounter
}

package "Sound" {
  class "ThreadedSoundManager" as ThreadedSoundManager
  class "SoundManager" as SoundManager
  class "MotorSound" as MotorSound
}

package "Logger" {
  class "MultiLogger" as MultiLogger
  class "PyLogger" as PyLogger
  class "MqttLogger" as MqttLogger
}

package "Simulation" {
  class "Orchestrator" as Orchestrator
  class "SignalReceiver" as SimulationSignalReceiver
  class "TerminalRenderer" as TerminalRenderer
}

package "Entry Point" {
  class "Main" as Main
}

Main --> GameMain : Initializes
Main --> DisplayManager : Displays
Main --> RoundCounter : Displays
Main --> ThreadedSoundManager : Plays sounds
Main --> MultiLogger : Logs

PhysicalController --> SignalTransmitter : ADC / digital inputs
SignalTransmitter --> SignalReceiver : UART Signal
ISignalReceiver <|.. SignalReceiver

PlayerController --> Vehicle : Updates state

DisplayManager --> LedDisplay : Virtual Buffers (RGB)
DisplayManager *-- Config : Configurations
DisplayManager *-- ColorConstants : Colors


ThreadedSoundManager *-- SoundManager
SoundManager *-- MotorSound

MultiLogger *-- PyLogger
MultiLogger *-- MqttLogger

Orchestrator --> TerminalRenderer : Renders State
Orchestrator *-- SimulationSignalReceiver : Uses

' Layout positioning
MotorSound -[hidden]down-> Orchestrator
DrivingProfile -[hidden]down-> PhysicalController
DrivingProfile-[hidden]down-> PlayerController
@enduml