cd .docs/tech-rep/

@REM Delete auxiliary files generated by LaTeX compilation
del *.aux
del *.bbl
del *.bcf
del *.blg
del *.log
del *.out
del *.run.xml
del *.tex.bbl
del *.tex.blg
del *.upa
del *.upb

pdflatex main
pdflatex main
biber main
pdflatex main
pdflatex main